on: 
  workflow_dispatch:
    inputs:
      component:
        description: 'Which Dapr Component? [basket|customer|inventory|payment|product]'     
        required: true  
name: Build, Containerize and push specified container dapr
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SHOWCASE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_PASSWORD }}
    - run: |
        cd ./src/dapr
        docker build -f dapr.gql.${{ github.event.inputs.component }}/Dockerfile . -t ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/dapr.gql.${{ github.event.inputs.component }}:${{ github.sha }}
        docker push ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/dapr.gql.${{ github.event.inputs.component }}:${{ github.sha }}
