on: 
  workflow_dispatch:
name: Build, Containerize and push micro front ends
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      # Log into Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SHOWCASE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_PASSWORD }}
    - run: |
        cd ./src/micro-front-ends/consumer/portal
        npm ci
        npm run-script dist:build
        docker build . -t ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-portal:${{ github.sha }}
        docker push ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-portal:${{ github.sha }}
        cd ../product
        npm ci
        npm run-script dist:build
        docker build . -t ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-product:${{ github.sha }}
        docker push ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-product:${{ github.sha }}
        cd ../cdn
        docker build . -t ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-cdn:${{ github.sha }}
        docker push ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-cdn:${{ github.sha }}
