on: 
  workflow_dispatch:
    inputs:
      component:
        description: 'Which Frontend Component? [product|portal]'     
        required: true
name: Build, Containerize and push specified Micro Frontend
jobs:
  build-and-deploy:
    if: github.event.inputs.component == 'product' || github.event.inputs.component == 'portal'
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      # Log into Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SHOWCASE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_PASSWORD }}
    - run: |
        cd ./src/micro-front-ends/consumer/${{ github.event.inputs.component }}
        npm ci
        npm run-script dist:build
        docker build . -t ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-${{ github.event.inputs.component }}:${{ github.sha }}
        docker push ${{ secrets.AZURE_SHOWCASE_CONTAINER_REGISTRY_NAME }}.azurecr.io/cb-mf-${{ github.event.inputs.component }}:${{ github.sha }}
